name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_analytics: ^10.10.6
  firebase_core:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: sbifx/v2.31.1
      path: packages/firebase_core/firebase_core
  firebase_in_app_messaging: ^0.7.5+6
  firebase_in_app_messaging_platform_interface: ^0.2.4+34
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
