name: firebase_performance_web
description: Web implementation of Firebase Performance monitoring.
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_performance/firebase_performance_web
version: 0.1.6+6

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: sbifx/v2.31.1
      path: packages/_flutterfire_internals
  firebase_core:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: sbifx/v2.31.1
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: sbifx/v2.31.1
      path: packages/firebase_core/firebase_core_web
  firebase_performance_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: sbifx/v2.31.1
      path: packages/firebase_performance/firebase_performance_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebasePerformanceWeb
        fileName: firebase_performance_web.dart
